# Built with Jekyll 3.2.0

# Setup
title:               Hombres Necios
tagline:             "A Student's Guide"
description:         "Hombres Necios: A Student's Guide es una edición digital del poema de Sor Juana Inés de la Cruz diseñada para profesores y estudiantes de español."
url:                 'http://fak2119.github.io'
baseurl:             ''

# About/contact
author:
  name:              Fiona Kibblewhite
  url:               
  email:             

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]

sass:
  sass_dir: _sass

